clang++ -fsierra -I.. -lSDL2 -ffast-math -O3 -DLENGTH=1 -mavx volume.cpp
clang++ -fsierra -I.. -lSDL2 -ffast-math -O3 -DLENGTH=8 -mavx volume.cpp
./a.out camera.dat density_highres.vol

clang++ -fsierra -I.. -lSDL2 -ffast-math -O3 -DLENGTH=1 -mavx aobench.cpp
clang++ -fsierra -I.. -lSDL2 -ffast-math -O3 -DLENGTH=8 -mavx aobench.cpp
./a.out
