clang++ -fsierra -I.. -ffast-math -O3 -DLENGTH=1 -mavx volume.cpp
clang++ -fsierra -I.. -ffast-math -O3 -DLENGTH=1 -mavx -DAVX volume.cpp
./a.out camera.dat density_highres.vol

clang++ -fsierra -I.. -ffast-math -O3 -DLENGTH=1 -mavx aobench.cpp
clang++ -fsierra -I.. -ffast-math -O3 -DLENGTH=1 -mavx -DAVX aobench.cpp
